server:
  port: 8088

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/little-humor/config.git
          search-paths: mall/{application}
  security:
    user:
      name: humor
      password: 123321!
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka.springcloud.cn/eureka







